title: mhbai
description: GitHub Pages 
baseurl: ""  # root repo 不需要
theme: jekyll-theme-slate  # 官方簡單主題，也可換其他
# 或其他支持的主题：
# theme: jekyll-theme-cayman  # 官方簡單主題，也可換其他
# jekyll-theme-minimal
# jekyll-theme-slate
# jekyll-theme-architect
# jekyll-theme-time-machine
# minima
